### ISSUE TITLE
App rework

### ISSUE THREAD

**Issue by lak1z-azk** [lak1z-azk/Azkili-PC-Assistant#2]
The old version might have issues with some of the steps. I'm currently on a full rework and update of the app. 
![image](https://user-images.githubusercontent.com/100957521/223402155-df7fae10-19ce-4e4e-aaac-a27aeb628a1b.png)

This is how the app will look like in future and will have new options.

**Comment by Lak1zz** [comment]
Main part from now on will have the small description, CPU usage, Available RAM and Network check.
Also will include with the latest system event logs that will show the error and information. Refreshes every 30min while app is running:
![image](https://user-images.githubusercontent.com/100957521/223491567-71de82e1-a516-48b3-86de-430bd4ab76e7.png)


PC Setup part will include basic part only. **NOTE INSTALLATION WON'T WORK IF YOU WON'T INSTALL CHOCOLATEY!**
It will check and install chocolatey. It will setup Time Zone and add This PC icon to your desktop. Also you will be able to choose your preferred additional keyboard layouts to install.
![image](https://user-images.githubusercontent.com/100957521/223491918-4ba167b8-718a-46d9-9e70-c10354843a60.png)

Windows Setup will include for now the same part as it was in the old version. But this time you will be able to choose if you want to disable or install additional features
![image](https://user-images.githubusercontent.com/100957521/223492130-c0116306-a69f-48bb-b7d2-4995b5052ee3.png)

Application setup will include several parts of apps to install. You can mark as much as you want and it will install only those that you choose
![image](https://user-images.githubusercontent.com/100957521/223492319-cffb1b16-7e66-4e03-97f0-a2aaefe3e26a.png)

User setup for now will include only 3 part of configuration:
1. Create a local user (it is good for those who's after installing windows sets first user as an admin and after creates a local user for a person/family) 
2. You will be able to change UAC level in app.
3. Firewall level also will be able to change from the app
![image](https://user-images.githubusercontent.com/100957521/223492672-13fe9b71-fc49-4b96-8154-a2eaabcab8be.png)

Utilities Setup will include basic Windows provided utility applications to easily reach them from one place. 
It will also will have a information about the tool on the right side when mouse is over the button
![image](https://user-images.githubusercontent.com/100957521/223492859-38d9752f-40f7-4361-9bfa-d1cc17964afc.png)


Stay tune for the updates.

**Comment by lak1z-azk** [comment]
Sorry for the delay of this update, but I'm facing few issues and some personal stuff also stopping me from continuing of this, but its not abbandoned and will be finished :) Just need time and patience for this.

**Comment by lak1z-azk** [comment]
Tool has been reworked with even newer design. New build will be uploaded today.
